from __future__ import annotations
from typing import Protocol, Iterable, Optional
from uuid import UUID
from .models import Echo, Trace, Pulse, Anchor

class EchoRepo(Protocol):
    async def save(self, echo: Echo) -> Echo: ...
    async def get(self, echo_id: UUID) -> Optional[Echo]: ...
    async def list(self, kind: Optional[str] = None, limit: int = 50) -> Iterable[Echo]: ...
    async def exists_idempotency(self, key: str) -> bool: ...

class TraceRepo(Protocol):
    async def save(self, trace: Trace) -> Trace: ...
    async def list_by_correlation(self, correlation_id: str, limit: int = 100) -> Iterable[Trace]: ...

class PulseSource(Protocol):
    async def now(self) -> Pulse: ...
    async def emit(self, note: str | None = None) -> Pulse: ...

class AnchorRepo(Protocol):
    async def upsert(self, key: str, kind: str, meta: dict | None = None) -> Anchor: ...
    async def get_by_key(self, key: str) -> Optional[Anchor]: ...
